{% set name = "python-subunit" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-subunit-{{ version }}.tar.gz
  sha256: 1079363131aa1d3f45259237265bc2e61a77e35f20edfb6e3d1d2558a2cdea34

build:
  noarch: python
  number: 0
  script: "python -m pip install . -vv"
requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - iso8601
    - testtools >=0.9.34

test:
  requires:
    - python {{ python_min }}
  imports:
    - subunit

about:
  home: https://launchpad.net/subunit
  license: Apache-2.0 OR BSD-3-Clause
  license_file: COPYING
  summary: 'Subunit is a streaming protocol for test results'


extra:
  recipe-maintainers:
    # - RajeeGit    # seems to be inactive
    - wshanks
